#My own modified version of ColdClientLoader originally by Rat431
[SteamClient]
Exe=Dock_64.exe
ExeRunDir=.
ExeCommandLine=
#IMPORTANT:
AppId=1787090

SteamClientDll=steamclient.dll
SteamClient64Dll=steamclient64.dll
