; Copyright ?Microsoft Corp.

[Theme]
; Windows 7 - IDS_THEME_DISPLAYNAME_Big Sur Dark Mode
DisplayName=Big Sur¡¤ºÚ°×
SetLogonBackground=0

; Computer - SHIDI_SERVER
[CLSID\{20D04FE0-3AEA-1069-A2D8-08002B30309D}\DefaultIcon]
DefaultValue=%SystemRoot%\System32\imageres.dll,-109

; UsersFiles - SHIDI_USERFILES
[CLSID\{59031A47-3F72-44A7-89C5-5595FE6B30EE}\DefaultIcon]
DefaultValue=%SystemRoot%\System32\imageres.dll,-123

; Network - SHIDI_MYNETWORK
[CLSID\{F02C1A0D-BE21-4350-88B0-7367FC96EF3C}\DefaultIcon]
DefaultValue=%SystemRoot%\System32\imageres.dll,-25

; Recycle Bin - SHIDI_RECYCLERFULL SHIDI_RECYCLER
[CLSID\{645FF040-5081-101B-9F08-00AA002F954E}\DefaultIcon]
Full=%SystemRoot%\System32\imageres.dll,-54
Empty=%SystemRoot%\System32\imageres.dll,-55


[Control Panel\Cursors]
AppStarting=%SystemRoot%\resources\Themes\Big Sur\cursors\Working.ani
Arrow=%SystemRoot%\resources\Themes\Big Sur\cursors\macNormSel.cur
Crosshair=%SystemRoot%\resources\Themes\Big Sur\cursors\Cross.cur
Hand=%SystemRoot%\resources\Themes\Big Sur\cursors\Hand.cur
Help=%SystemRoot%\resources\Themes\Big Sur\cursors\Help.cur
IBeam=%SystemRoot%\resources\Themes\Big Sur\cursors\Beam.cur
No=%SystemRoot%\resources\Themes\Big Sur\cursors\Unavailable.cur
NWPen=%SystemRoot%\resources\Themes\Big Sur\cursors\Pen.cur
SizeAll=%SystemRoot%\resources\Themes\Big Sur\cursors\Resize All.cur
SizeNESW=%SystemRoot%\resources\Themes\Big Sur\cursors\Resize Left.cur
SizeNS=%SystemRoot%\resources\Themes\Big Sur\cursors\Size Horz.cur
SizeNWSE=%SystemRoot%\resources\Themes\Big Sur\cursors\Resize Right.cur
SizeWE=%SystemRoot%\resources\Themes\Big Sur\cursors\Size Vert.cur
UpArrow=%SystemRoot%\resources\Themes\Big Sur\cursors\Alternate.cur
Wait=%SystemRoot%\resources\Themes\Big Sur\cursors\Busy.ani
DefaultValue=[ÖÂÃÀ»¯] Mac

[Control Panel\Desktop]
Wallpaper=%SystemRoot%\Resources\Themes\Big Sur\03\zhutix.png
TileWallpaper=0
WallpaperStyle=10
Pattern=

[VisualStyles]
Path=%SystemRoot%\Resources\Themes\Big Sur\Big Sur Dark Mode.msstyles
ColorStyle=NormalColor
Size=NormalSize
AutoColorization=0
ColorizationColor=0XFF191919
SystemMode=Dark
AppMode=Dark
[boot]
SCRNSAVE.EXE=

[MasterThemeSelector]
MTSM=RJSPBS

[Slideshow]

Interval=900000
Shuffle=1
ImagesRootPath=%SystemRoot%\Resources\Themes\Big Sur\03\